/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.awt.*;
import javax.swing.*;
import java.io.File;

/**
 *
 * @author 53iky0
 */
public class Mazerthon extends javax.swing.JFrame {

    /**
     * Creates new form menuFrame
     */
    public Mazerthon() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        soloButton = new javax.swing.JButton();
        botButton = new javax.swing.JButton();
        tutorialButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 450));
        setName("menuFrame"); // NOI18N
        setSize(new java.awt.Dimension(400, 450));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bungee Shade", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MAZERTHON");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 50));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 360, 100);
        jLabel1.setFont(new java.awt.Font("Lato", 1, 36));

        soloButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        soloButton.setText("SOLO");
        soloButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        soloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soloButtonActionPerformed(evt);
            }
        });
        getContentPane().add(soloButton);
        soloButton.setBounds(100, 110, 200, 50);

        botButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botButton.setText("BOT MATCH");
        botButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botButton.setMaximumSize(new java.awt.Dimension(200, 50));
        botButton.setMinimumSize(new java.awt.Dimension(200, 50));
        botButton.setPreferredSize(new java.awt.Dimension(200, 50));
        botButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botButton);
        botButton.setBounds(100, 170, 200, 50);

        tutorialButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tutorialButton.setText("TUTORIAL");
        tutorialButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tutorialButton.setMaximumSize(new java.awt.Dimension(200, 50));
        tutorialButton.setMinimumSize(new java.awt.Dimension(200, 50));
        tutorialButton.setPreferredSize(new java.awt.Dimension(200, 50));
        tutorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialButtonActionPerformed(evt);
            }
        });
        getContentPane().add(tutorialButton);
        tutorialButton.setBounds(100, 230, 200, 50);

        settingsButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        settingsButton.setText("SETTINGS");
        settingsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        settingsButton.setMaximumSize(new java.awt.Dimension(200, 50));
        settingsButton.setMinimumSize(new java.awt.Dimension(200, 50));
        settingsButton.setPreferredSize(new java.awt.Dimension(200, 50));
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(settingsButton);
        settingsButton.setBounds(100, 290, 200, 50);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/bgretro.jpg"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(400, 450));
        Background.setMinimumSize(new java.awt.Dimension(400, 450));
        Background.setPreferredSize(new java.awt.Dimension(400, 450));
        getContentPane().add(Background);
        Background.setBounds(-90, -20, 500, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soloButtonActionPerformed
        Solo_Stage sf = new Solo_Stage();
        this.setVisible(false);
        sf.setVisible(true);
    }//GEN-LAST:event_soloButtonActionPerformed

    private void botButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botButtonActionPerformed
        Bot_Stage bs1 = new Bot_Stage();
        this.setVisible(false);
        bs1.setVisible(true);
    }//GEN-LAST:event_botButtonActionPerformed

    private void tutorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialButtonActionPerformed
        Tutorial t = new Tutorial();
        this.setVisible(false);
        t.setVisible(true);
    }//GEN-LAST:event_tutorialButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        Settings s = new Settings();
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_settingsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Mazerthon();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            
                
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mazerthon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mazerthon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mazerthon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mazerthon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mazerthon().setVisible(true);
            }
        });        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton botButton;
    private static javax.swing.JLabel jLabel1;
    private javax.swing.JButton settingsButton;
    private javax.swing.JButton soloButton;
    private javax.swing.JButton tutorialButton;
    // End of variables declaration//GEN-END:variables
}
