/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author 53iky0
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form botFrame
     */
    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        subTitle = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        bgmSlider = new javax.swing.JSlider();
        sfxSlider = new javax.swing.JSlider();
        muteToggleButton = new javax.swing.JToggleButton();
        bgmLabel = new javax.swing.JLabel();
        sfxLabel = new javax.swing.JLabel();
        contentLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        topPanel.setBackground(new java.awt.Color(153, 153, 153));
        topPanel.setMaximumSize(new java.awt.Dimension(400, 50));
        topPanel.setMinimumSize(new java.awt.Dimension(400, 50));
        topPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        subTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        subTitle.setText("SETTINGS");

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/back.png"))); // NOI18N
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backButton.setMaximumSize(new java.awt.Dimension(30, 30));
        backButton.setMinimumSize(new java.awt.Dimension(30, 30));
        backButton.setPreferredSize(new java.awt.Dimension(30, 30));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(subTitle)
                .addGap(200, 200, 200))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subTitle))
                .addGap(10, 10, 10))
        );

        getContentPane().add(topPanel);
        topPanel.setBounds(0, 0, 400, 50);

        bgmSlider.setMaximumSize(new java.awt.Dimension(200, 40));
        bgmSlider.setMinimumSize(new java.awt.Dimension(200, 40));
        bgmSlider.setPreferredSize(new java.awt.Dimension(200, 40));
        getContentPane().add(bgmSlider);
        bgmSlider.setBounds(100, 110, 200, 40);

        sfxSlider.setMaximumSize(new java.awt.Dimension(200, 40));
        sfxSlider.setMinimumSize(new java.awt.Dimension(200, 40));
        sfxSlider.setPreferredSize(new java.awt.Dimension(200, 40));
        getContentPane().add(sfxSlider);
        sfxSlider.setBounds(100, 210, 200, 40);

        muteToggleButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        muteToggleButton.setText("Mute");
        muteToggleButton.setMaximumSize(new java.awt.Dimension(80, 50));
        muteToggleButton.setMinimumSize(new java.awt.Dimension(80, 50));
        muteToggleButton.setPreferredSize(new java.awt.Dimension(80, 50));
        getContentPane().add(muteToggleButton);
        muteToggleButton.setBounds(160, 280, 80, 50);

        bgmLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bgmLabel.setForeground(new java.awt.Color(255, 255, 0));
        bgmLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgmLabel.setText("BGM");
        bgmLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bgmLabel.setMaximumSize(new java.awt.Dimension(80, 40));
        bgmLabel.setMinimumSize(new java.awt.Dimension(80, 40));
        bgmLabel.setPreferredSize(new java.awt.Dimension(80, 40));
        getContentPane().add(bgmLabel);
        bgmLabel.setBounds(160, 70, 80, 40);
        bgmLabel.getAccessibleContext().setAccessibleName("SFX");

        sfxLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sfxLabel.setForeground(new java.awt.Color(255, 255, 0));
        sfxLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sfxLabel.setText("SFX");
        sfxLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sfxLabel.setMaximumSize(new java.awt.Dimension(80, 40));
        sfxLabel.setMinimumSize(new java.awt.Dimension(80, 40));
        sfxLabel.setPreferredSize(new java.awt.Dimension(80, 40));
        getContentPane().add(sfxLabel);
        sfxLabel.setBounds(160, 170, 80, 40);

        contentLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        contentLabel.setForeground(new java.awt.Color(0, 51, 204));
        contentLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/bg01.jpg"))); // NOI18N
        contentLabel.setText("BOT LEVEL");
        contentLabel.setMaximumSize(new java.awt.Dimension(400, 300));
        contentLabel.setMinimumSize(new java.awt.Dimension(400, 300));
        contentLabel.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(contentLabel);
        contentLabel.setBounds(0, 50, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Mazerthon m = new Mazerthon();
        this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bgmLabel;
    private javax.swing.JSlider bgmSlider;
    private javax.swing.JLabel contentLabel;
    private javax.swing.JToggleButton muteToggleButton;
    private javax.swing.JLabel sfxLabel;
    private javax.swing.JSlider sfxSlider;
    private javax.swing.JLabel subTitle;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
